version: "3"


networks:
   docky:
      ipam:
         driver: default
         config:
            - subnet: 10.1.0.0/24

services:
   web:
      image: nginx:latest
      container_name: nginx
      restart: always
      ports:
         - "55488:80"
      restart: "always"
      links:
         - mariadb
      depends_on:
         - mariadb
         - php
      volumes:
         - ./code:/code
         - ./config/nginx/site.conf:/etc/nginx/conf.d/default.conf
      networks:
         docky:
            ipv4_address: 10.1.0.100

   php:
      build: ./config/php/Dockerfile
      container_name: php
      depends_on:
         - mariadb
      volumes:
         - ./code:/code
         - ./config/php/php-log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
      networks:
         docky:
            ipv4_address: 10.1.0.101

   mariadb:
      image: mariadb
      container_name: mariadb
      restart: "always"
      ports:
         - "53306:3306"
      volumes:
         - dbdata:/var/lib/mysql
         - ./config/mariadb/dbinit/:/docker-entrypoint-initdb.d/
      environment:
         MYSQL_ROOT_PASSWORD: o
         MYSQL_USER: o
         MYSQL_PASSWORD: o
      networks:
         docky:
            ipv4_address: 10.1.0.102

volumes:
   dbdata:

