version: "3"


services:
   web:
      image: nginx
      container_name: nginx
      restart: always
      ports:
         - "55488:80"
      restart: "always"
      depends_on:
         - mariadb
         - php
      volumes:
         - ./code:/code
         - ./config/nginx/site.conf:/etc/nginx/conf.d/default.conf

   php:
      build: ./config/php/dockerfile
      container_name: php
      depends_on:
         - mariadb
      volumes:
         - ./code:/code
         - ./config/php/php-log.conf:/usr/local/etc/php-fpm.d/zz-log.conf

   mariadb:
      image: mariadb
      container_name: mariadb
      command: --default-authentication-plugin=mysql_native_password
      restart: "always"
      ports:
         - "53306:3306"
      volumes:
         - dbdata:/var/lib/mysql
         - ./config/mariadb/dbinit/:/docker-entrypoint-initdb.d/
      environment:
         MYSQL_ROOT_PASSWORD: o
         MYSQL_USER: o
         MYSQL_PASSWORD: o

volumes:
   dbdata:

