version: "3"

networks:
   carsides-external:
      name: "carsides-external"
      external: true
   carsides-internal:
      name: "carsides-internal"
      external: false

services:
   web:
      image: nginx
      container_name: carsides_web
      restart: always
      ports:
         - "20100:80"
      restart: "always"
      depends_on:
         - mariadb
         - php
      labels:
      - traefik.http.routers.web.rule=Host(`carsides.coci.result.si`)
      - traefik.http.routers.web.tls=true
      - traefik.enable=true
      networks:
         - carsides-external
         - carsides-internal
      volumes:
         - ./code:/code
         - ./config/nginx/site.conf:/etc/nginx/conf.d/default.conf

   php:
      build: ./config/php/dockerfile
      container_name: carsides_php
      depends_on:
         - mariadb
      labels:
         - traefik.enable=false
      networks:
         - carsides-internal
      volumes:
         - ./code:/code
         - ./config/php/php-log.conf:/usr/local/etc/php-fpm.d/zz-log.conf

   mariadb:
      image: mariadb
      container_name: carsides_mariadb
      command: --default-authentication-plugin=mysql_native_password
      environment:
         MYSQL_ROOT_PASSWORD: o
         MYSQL_USER: o
         MYSQL_PASSWORD: o
      restart: "always"
      ports:
         - "53306:3306"
      labels:
         - traefik.enable=false
      networks:
         - carsides-internal
      volumes:
         - dbdata:/var/lib/mysql
         - ./config/mariadb/dbinit/:/docker-entrypoint-initdb.d/

volumes:
   dbdata:
